version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  api:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    volumes:
      - ../.:/app/
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn plus_balance.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env

  bot:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    volumes:
      - ../.:/app/
    restart: always
    command: >
      sh -c "python3 bot/main.py"
    depends_on:
      - api
    env_file:
      - .env
    environment:
      - debug=INFO

volumes:
  postgres_data: