version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  api:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    volumes:
      - ../.:/app/
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && python3 manage.py migrate && gunicorn plus_balance.wsgi:application --bind 0.0.0.0:8000"

  bot:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    volumes:
      - ../.:/app/
    restart: always
    command: >
      sh -c "python3 bot/main.py"
    depends_on:
      - api
