version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  api:
    build:
      context: ../.
      dockerfile: Dockerfile
    image: budget-bot-api
    restart: always
    depends_on:
      - db
      - migration

  bot:
    build:
      context: ../bot/.
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api

  migration:
    image: budget-bot-api
    command: "python3 /app/manage.py migrate --no-input && python3 /app/manage.py load_categories.py"
    depends_on:
      - db