version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  api:
    build:
      context: ../.
      dockerfile: Dockerfile
    image: budgetbot_api
    restart: always
    depends_on:
      - db
    command: >
      sh -c "python3 /app/manage.py migrate && python3 /app/manage.py load_categories"

  bot:
    build:
      context: ../bot/.
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
