name: my_budget

on:
  push:
    branches:
      - main

jobs:

  get_all_modified_files_and_send_messages:
    runs-on: ubuntu-latest
    name: Test changed-files
    environment: vdsina
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
      - name: List all changed files
        run: |
          for f in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$f was created/modified/deleted"
          done
      - name: Notify me
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MY_TG_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ${{ github.workflow }} created by ${{ github.actor }}.
            
            Commit message:
            ${{ github.event.head_commit.message }}
            
            Added files:
            ${{ steps.changed-files.outputs.added_files }}
            
            Modified files:
            ${{ steps.changed-files.outputs.modified_files }}
            
            Deleted files:
            ${{ steps.changed-files.outputs.deleted_files }}
            

#  build_and_push_to_docker_hub:
#    name: Push Docker image to Docker Hub
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    environment: vdsina
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to Docker
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v4
#        with:
#          context: compose
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/budget_calculator:latest

#  build_and_load:
#    runs-on: ubuntu-latest
#    environment: vdsina
#    needs: build_and_push_to_docker_hub
#    steps:
#      - name: Executing remote ssh commands to deploy
#        id: compose
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST_IP }}
#          username: ${{ secrets.HOST_USER }}
#          key: ${{ secrets.HOST_PUBLIC_KEY }}
#          port: ${{ secrets.HOST_PORT }}
#          script: |
#            cd budget_calculator_api/
#            git pull
#            docker compose -f compose/docker-compose.yaml down
#            docker compose -f compose/docker-compose.yaml up -d
#            docker ps -a | grep compose
